# Generated by Django 3.2.8 on 2021-11-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211110_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloths',
            new_name='Cloth',
        ),
    ]
