# Generated by Django 3.2.8 on 2021-11-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_cloths_cloth'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cloth'),
        ),
    ]
