# Generated by Django 3.2.8 on 2021-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
